In [13]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np

In [14]:

# def calculate_oscilloscope_uncertainty(najpod, u_b = 0):
#     return np.sqrt((najpod**2 + u_b**2) /3) 

def calculate_analog_meter_uncertainties(klasa, zakres, najpod=0, u_be=0):
    return np.sqrt(((klasa*zakres)**2 + najpod**2 + u_be**2)/3)

def calculate_sole_b_uncertainty(series, u_b, u_be=0):
    return np.sqrt(series/series*((u_b**2)/3 + (u_be**2)/3))

# def calculate_digital_meter_deltas(series, klasa, dgt):
#     delta_x = klasa * series + dgt
#     return series/series * delta_x
    
# def calculate_digital_meter_uncertainties(series, klasa, dgt):
#     return calculate_digital_meter_deltas(series,klasa,dgt)/np.sqrt(3)

def calculate_sanwa_uncertainties(series, c1, c2, zakres):
    return (c1*series + c2*zakres)/np.sqrt(3)
    
#private functions
def calculate_B(Ic):
    return 0.00673 + 0.18548*Ic + 0.00217*Ic**2 - 0.00318 *Ic**3 + 2.00009e-4 * Ic**4

In [15]:
_a = 4e-3 #m
_d = 0.3e-6 #m
_l = 7.8e-3 #m
_e = 1.60217663e-19 #C

In [16]:

Ic_klasa = 0.005 #0.5%
Ic = pd.DataFrame({
    "Ic": [
        1,
        2,
        3,
        3.5,
        4,
        4.5,
        5,
        5.5,
    ],
})

Ic["zakres"] = [7.5 for x in range(len(Ic["Ic"]))]
Ic["najpod"] = [0.1 for x in range(len(Ic["Ic"]))]
Ic["u"] = calculate_analog_meter_uncertainties(Ic_klasa, Ic["zakres"], Ic["najpod"], Ic["najpod"]/2)

Ic.to_csv("csv/Ic.csv", index=False)
Ic

    Ic  zakres  najpod         u
0  1.0     7.5     0.1  0.068084
1  2.0     7.5     0.1  0.068084
2  3.0     7.5     0.1  0.068084
3  3.5     7.5     0.1  0.068084
4  4.0     7.5     0.1  0.068084
5  4.5     7.5     0.1  0.068084
6  5.0     7.5     0.1  0.068084
7  5.5     7.5     0.1  0.068084

In [17]:
B = pd.DataFrame()
B["B"] = calculate_B(Ic["Ic"])
B["u"] = np.sqrt((0.18548 + 0.00434*Ic["Ic"] - 0.00954*Ic["Ic"]**2 + 8.00036e-4 *Ic["Ic"]**3)**2 * Ic["u"]/3)
B.to_csv("csv/B.csv", index=False)

In [18]:
#250mV
U_niesymetryzacji_150 = 0.03e-3 #V
Uh_150 = pd.DataFrame({
    "Uh": [
        0.68e-3,
        1.37e-3,
        1.98e-3,
        2.22e-3,
        2.43e-3,
        2.58e-3,
        2.72e-3,
        2.84e-3
    ],
})
Uh_150["zakres"] = [0.5 for x in range(len(Uh_150["Uh"]))]
Uh_150["c1"] = [0.03e-2 for x in range(len(Uh_150["Uh"]))]
Uh_150["c2"] = [0.02e-2 for x in range(len(Uh_150["Uh"]))]
Uh_150["u"] = calculate_sanwa_uncertainties(Uh_150["Uh"], Uh_150["c1"], Uh_150["c2"], Uh_150["zakres"])

Uh_150.to_csv("csv/Uh_150.csv", index=False)
Uh_150

        Uh  zakres      c1      c2         u
0  0.00068     0.5  0.0003  0.0002  0.000058
1  0.00137     0.5  0.0003  0.0002  0.000058
2  0.00198     0.5  0.0003  0.0002  0.000058
3  0.00222     0.5  0.0003  0.0002  0.000058
4  0.00243     0.5  0.0003  0.0002  0.000058
5  0.00258     0.5  0.0003  0.0002  0.000058
6  0.00272     0.5  0.0003  0.0002  0.000058
7  0.00284     0.5  0.0003  0.0002  0.000058

In [19]:
#250mV
U_niesymetryzacji_250 = 0.06e-3 #V
Uh_250 = pd.DataFrame({
    "Uh": [
        1.08e-3,
        2.19e-3,
        3.18e-3,
        3.57e-3,
        3.90e-3,
        4.16e-3,
        4.38e-3,
        4.57e-3,
    ],
})
Uh_250["zakres"] = [0.5 for x in range(len(Uh_250["Uh"]))]
Uh_250["c1"] = [0.03e-2 for x in range(len(Uh_250["Uh"]))]
Uh_250["c2"] = [0.02e-2 for x in range(len(Uh_250["Uh"]))]
Uh_250["u"] = calculate_sanwa_uncertainties(Uh_250["Uh"], Uh_250["c1"], Uh_250["c2"], Uh_250["zakres"])

Uh_250.to_csv("csv/Uh_250.csv", index=False)
Uh_250

        Uh  zakres      c1      c2         u
0  0.00108     0.5  0.0003  0.0002  0.000058
1  0.00219     0.5  0.0003  0.0002  0.000058
2  0.00318     0.5  0.0003  0.0002  0.000058
3  0.00357     0.5  0.0003  0.0002  0.000058
4  0.00390     0.5  0.0003  0.0002  0.000058
5  0.00416     0.5  0.0003  0.0002  0.000058
6  0.00438     0.5  0.0003  0.0002  0.000058
7  0.00457     0.5  0.0003  0.0002  0.000059

In [20]:
#250mV
U_niesymetryzacji_350 = 0.09e-3 #V
Uh_350 = pd.DataFrame({
    "Uh": [
        1.53e-3,
        3.05e-3,
        4.43e-3,
        4.99e-3,
        5.43e-3,
        5.80e-3,
        6.10e-3,
        6.36e-3
    ],
})
Uh_350["zakres"] = [0.5 for x in range(len(Uh_350["Uh"]))]
Uh_350["c1"] = [0.03e-2 for x in range(len(Uh_350["Uh"]))]
Uh_350["c2"] = [0.02e-2 for x in range(len(Uh_350["Uh"]))]
Uh_350["u"] = calculate_sanwa_uncertainties(Uh_350["Uh"], Uh_350["c1"], Uh_350["c2"], Uh_350["zakres"])

Uh_350.to_csv("csv/Uh_350.csv", index=False)
Uh_350

        Uh  zakres      c1      c2         u
0  0.00153     0.5  0.0003  0.0002  0.000058
1  0.00305     0.5  0.0003  0.0002  0.000058
2  0.00443     0.5  0.0003  0.0002  0.000059
3  0.00499     0.5  0.0003  0.0002  0.000059
4  0.00543     0.5  0.0003  0.0002  0.000059
5  0.00580     0.5  0.0003  0.0002  0.000059
6  0.00610     0.5  0.0003  0.0002  0.000059
7  0.00636     0.5  0.0003  0.0002  0.000059

In [21]:
# x - na plytce w - wzorcowe
U_x = 32.65e-3 #mv
U_w = 15.61e-3 #mV
R_w = 100
R_x = U_x/U_w * R_w
R_x

209.16079436258806

In [22]:

U_niesymetryzacji_350 = 0.09e-3 #V
Uw = pd.DataFrame()
Uw["Uw"] = [15.61e-3 for x in range(len(Ic["Ic"]))] 
Uw["zakres"] = [0.5 for x in range(len(Uw["Uw"]))]
Uw["c1"] = [0.03e-2 for x in range(len(Uw["Uw"]))]
Uw["c2"] = [0.02e-2 for x in range(len(Uw["Uw"]))]
Uw["u"] = calculate_sanwa_uncertainties(Uw["Uw"], Uw["c1"], Uw["c2"], Uw["zakres"])

Uw.to_csv("csv/Ux.csv", index=False)
Uw

        Uw  zakres      c1      c2        u
0  0.01561     0.5  0.0003  0.0002  0.00006
1  0.01561     0.5  0.0003  0.0002  0.00006
2  0.01561     0.5  0.0003  0.0002  0.00006
3  0.01561     0.5  0.0003  0.0002  0.00006
4  0.01561     0.5  0.0003  0.0002  0.00006
5  0.01561     0.5  0.0003  0.0002  0.00006
6  0.01561     0.5  0.0003  0.0002  0.00006
7  0.01561     0.5  0.0003  0.0002  0.00006

In [23]:

Ux = pd.DataFrame({
    "Ux": [
        32.65e-3,
        33.29e-3,
        33.70e-3,
        33.96e-3,
        34.18e-3,
        34.37e-3,
        34.52e-3,
        34.69e-3
    ],
})
Ux["zakres"] = [0.5 for x in range(len(Ux["Ux"]))]
Ux["c1"] = [0.03e-2 for x in range(len(Ux["Ux"]))]
Ux["c2"] = [0.02e-2 for x in range(len(Ux["Ux"]))]
Ux["u"] = calculate_sanwa_uncertainties(Ux["Ux"], Ux["c1"], Ux["c2"], Ux["zakres"])

Ux.to_csv("csv/Ux.csv", index=False)
Ux

Rx = pd.DataFrame()
Rx["Rx"] = Ux["Ux"]/Uw["Uw"] * 100
Rx["u"] = np.sqrt((1/Uw["Uw"]*100)**2*Ux["u"]**2 + (Ux["Ux"]/Uw["Uw"]**2 * 100)**2 * Uw["u"]**2)
Rx.to_csv("csv/Rx.csv", index=False)
Rx

           Rx         u
0  209.160794  0.905941
1  213.260730  0.920472
2  215.887252  0.929804
3  217.552851  0.935731
4  218.962204  0.940752
5  220.179372  0.945092
6  221.140295  0.948521
7  222.229340  0.952410